### ISSUE TITLE
not logging into file.

### ISSUE THREAD

**Issue by staminna** [mozilla/csp-logger#19]
I have created an CSP-policy, Report-only, and set into .htaccess file. I have validated the CSP and it is correct.
If I remove any CSP instruction, I can see it on the browser console, and it works.
I set the config file to listen to port 8212 and whitelisted the domains I wanted to keep a check of log.

But apparently, the browser is not sending any report or writing to the /tmp/csp.log file.

**Comment by naugtur** [comment]
Hi,

If anything is wrong with csp-logger, please share a complete setup to reproduce (as repository or as gist) or point to a specific error and reopen the issue.
If you need support setting up, this is not where you get it. stackoverflow could work.
